name = "myai-photos-proxy"
main = "index.js"
compatibility_date = "2024-03-11"

# Routes are now configured differently
routes = [
  { pattern = "myai.photos/*", zone_name = "myai.photos" }
]

# If you need cron triggers, use this format instead:
# [triggers]
# crons = ["*/5 * * * *"]